name: Validazione File Domande
on:
  push:
    branches:
      - main
      
defaults:
  run:
    shell: bash

jobs:
  Validazione-File-Domande:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: cd ${{ github.workspace }}
      - name: Controllo Codifica File
        run: |
          file_domande="Domande.txt"
          codifica="UTF-8"
          
          # Check Encoding
          charset=$(file -i "$file_domande" | cut -f 2 -d ";" | cut -f 2 -d "=")
          if [[ "${charset^^}" = "$codifica" ]]
          then
            echo "✔️ DEUBG: Codifica OK ($charset)"
          else
            echo "❌ ERRORE: Codifica file \"$file_domande\" errata ($charset)"
            exit 1
          fi
